// Runs the real converters in headless Chromium against fixtures generated by python-docx/openpyxl/python-pptx/LibreOffice.
import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from '../../scripts/dev.mjs';

const dir = path.dirname(fileURLToPath(import.meta.url));
const fx = path.join(dir, '..', 'fixtures');
const server = createServer(); await new Promise((r) => server.listen(0, r));
const base = `http://localhost:${server.address().port}`;
const browser = await chromium.launch();
const page = await browser.newPage();
const errors = []; page.on('pageerror', (e) => errors.push(String(e))); page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
await page.goto(`${base}/index.html`);
const results = {};
for (const f of ['sample.docx', 'sample.pptx', 'sample.xlsx', 'sample.csv', 'sample.html', 'sample.txt', 'sample.pdf', 'english.pdf']) {
  const b64 = fs.readFileSync(path.join(fx, f)).toString('base64');
  results[f] = await page.evaluate(async ({ name, b64 }) => {
    const bytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
    const file = new File([bytes], name);
    const { convertFile } = await import('/js/modules/converters/index.js');
    try { const r = await convertFile(file, { maxBytes: 25 * 1024 * 1024, timeoutMs: 60000 }); return { ok: true, md: r.markdown, w: r.warnings, fn: r.filename }; }
    catch (e) { return { ok: false, code: e.code, msg: e.message, detail: e.detail }; }
  }, { name: f, b64 });
}
fs.writeFileSync('/tmp/conv-results.json', JSON.stringify(results, null, 2));
for (const [k, v] of Object.entries(results)) { console.log(`\n===== ${k} ${v.ok ? '' : 'FAILED'} ${v.fn || ''}`); console.log(v.ok ? v.md : JSON.stringify(v)); if (v.w && v.w.length) console.log('warnings:', v.w); }
console.log('\npage errors:', errors);
await browser.close(); server.close();
